import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import { TextField, Button } from '@mui/material';

import Confirmation from '../components/Confirmation.jsx';
import Header from '../components/Header.jsx';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Workout YTracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className={styles.main}>

        <div class="top-nav">
        </div>
        <TextField id="outlined-basic" label="Insert URL.." variant="outlined" />
        <Button variant="contained">Add</Button>
        <Confirmation></Confirmation>
      </main>
    </>
  )
}
