import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

import { useState } from 'react';

import Header from '../components/Header.jsx';
import Add from '../components/Add.jsx';
import Form from '../components/Form.jsx';

const Home = () => {
  return (
    <>
      <Head>
        <title>Workout YTracker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.main}>
        <Add></Add>
        <Form></Form>
      </main>
    </>
  )
}

export default Home;
